[package]
name = "twyg"
description = "A tiny logging setup for Rust applications"
readme = "README.md"
version = "0.1.7"
license = "Apache-2.0"
authors = ["Duncan McGreggor <oubiwann@gmail.com>"]
repository = "https://github.com/oxur/twyg"
documentation = "https://docs.rs/twyg/"
categories = ["development-tools", "value-formatting"]
keywords = ["logging", "loggers", "formatting"]
exclude = ["/.github", "/resources", ".gitignore"]
edition = "2018"

[lib]
name = "twyg"

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.14"
serde = { version = "1.0.125", features = ["derive"] }

[dev-dependencies]
config = { version = "0.11.0", default-features = false, features = [ "yaml" ] }

[[example]]
name = "colour-caller"

[[example]]
name = "no-caller"

[[example]]
name = "no-colour"

[[example]]
name = "from-config"
