[package]
name = "twyg"
description = "A tiny logging setup for Rust applications"
readme = "README.md"
version = "0.1.7"
license = "Apache-2.0"
authors = ["Duncan McGreggor <oubiwann@gmail.com>"]
repository = "https://github.com/oxur/twyg"
documentation = "https://docs.rs/twyg/"
categories = ["development-tools", "value-formatting"]
keywords = ["logging", "loggers", "formatting"]
exclude = ["/.github", "/resources", ".gitignore"]
edition = "2018"

[lib]
name = "twyg"

[dependencies]
chrono = "0.4.10"
colored = "1.9.2"
fern = { version = "0.5.9", features = ["colored"] }
log = "0.4.6"
serde = { version = "1.0.104", features = ["derive"] }

[dev-dependencies]
config = "0.10.1"

[[example]]
name = "color-caller"

[[example]]
name = "no-caller"

#[[example]]
#name = "no-color"

#[[example]]
#name = "from-config"
